JJNG.Web/Areas/Branch/Controllers/BrhAddressAccountController.cs
using JJNG.Data;
using JJNG.Data.AppIdentity;
using JJNG.Data.Personnel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Threading.Tasks;

namespace JJNG.Web.Areas.Branch.Controllers
{
    [Area("Branch")]
    [Authorize(Roles = "Admins,前台,管家,前台审核,管家审核")]
    public class BrhAddressAccountController : Controller
    {
        private readonly AppDbContext _context;
        private readonly AppIdentityDbContext _identityContext;
        private UserManager<AppIdentityUser> _userManager;

        public BrhAddressAccountController(AppDbContext context, AppIdentityDbContext identitycontext, UserManager<AppIdentityUser> usrMgr)
        {
            _context = context;
            _identityContext = identitycontext;
            _userManager = usrMgr;
        }

        public async Task<IActionResult> Index()
        {
            AppIdentityUser _user = await _userManager.FindByNameAsync(User.Identity.Name);
            ViewData["UserName"] = _user.UserName;
            ViewData["Branch"] = _user.Branch;
            ViewData["Department"] = _user.Department;
            var psnAddressAccount = await _context.PsnAddressAccount.Where(x => x.Branch == _user.Branch&&(string.IsNullOrEmpty(x.Manager)||x.Manager==_user.UserName))
.ToListAsync();
            return View(psnAddressAccount);
        }
    }
}

JJNG.Web/Areas/Branch/Controllers/BrhAddressController.cs
using JJNG.Data;
using JJNG.Data.AppIdentity;
using JJNG.Data.Personnel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace JJNG.Web.Areas.Branch.Controllers
{
    [Area("Branch")]
    [Authorize(Roles = "Admins,前台,管家,前台审核,管家审核")]
    public class BrhAddressController : Controller
    {
        private readonly AppDbContext _context;
        private readonly AppIdentityDbContext _identityContext;
        private UserManager<AppIdentityUser> _userManager;

        public BrhAddressController(AppDbContext context, AppIdentityDbContext identitycontext, UserManager<AppIdentityUser> usrMgr)
        {
            _context = context;
            _identityContext = identitycontext;
            _userManager = usrMgr;
        }

        public async Task<IActionResult> Index(int? id)
        {
            AppIdentityUser _user = await _userManager.FindByNameAsync(User.Identity.Name);
            ViewData["UserName"] = _user.UserName;
            ViewData["Branch"] = _user.Branch;
            ViewData["AddressAccountId"] = id;

            return View(await _context.PsnAddress.Where(x => x.AddressAccountId == id).ToListAsync());
        }

        public async Task<IActionResult> Create(int? id)
        {
            AppIdentityUser _user = await _userManager.FindByNameAsync(User.Identity.Name);
            ViewData["UserName"] = _user.UserName;
            ViewData["Branch"] = _user.Branch;
            ViewData["AddressAccountId"] = id;
            return PartialView("~/Areas/Branch/Views/BrhAddress/CreateEdit.cshtml");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("AddressId,AddressAccountId,Name,Purpose,Phone,EnteringStaff,Branch,Address")] PsnAddress psnAddress)
        {
            if (ModelState.IsValid)
            {
                _context.Add(psnAddress);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index), new { id = psnAddress.AddressAccountId });
            }
            return PartialView("~/Areas/Branch/Views/BrhAddress/CreateEdit.cshtml", psnAddress);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var psnAddress = await _context.PsnAddress.SingleOrDefaultAsync(m => m.AddressId == id);
            AppIdentityUser _user = await _userManager.FindByNameAsync(User.Identity.Name);
            ViewData["UserName"] = _user.UserName;
            ViewData["Branch"] = _user.Branch;
            if (psnAddress == null)
            {
                return NotFound();
            }
            return PartialView("~/Areas/Branch/Views/BrhAddress/CreateEdit.cshtml", psnAddress);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("AddressId,AddressAccountId,Name,Purpose,Phone,EnteringStaff,Branch,Address")] PsnAddress psnAddress)
        {
            if (id != psnAddress.AddressId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(psnAddress);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PsnAddressExists(psnAddress.AddressId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index), new { id = psnAddress.AddressAccountId });
            }
            return PartialView("~/Areas/Branch/Views/BrhAddress/CreateEdit.cshtml", psnAddress);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var psnAddress = await _context.PsnAddress
                .SingleOrDefaultAsync(m => m.AddressId == id);
            if (psnAddress == null)
            {
                return NotFound();
            }

            return PartialView("~/Areas/Branch/Views/BrhAddress/Delete.cshtml", "这条记录");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int? id, IFormCollection form)
        {
            var psnAddress = await _context.PsnAddress.SingleOrDefaultAsync(m => m.AddressId == id);
            _context.PsnAddress.Remove(psnAddress);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index), new { id = psnAddress.AddressAccountId });
        }

        private bool PsnAddressExists(int id)
        {
            return _context.PsnAddress.Any(e => e.AddressId == id);
        }
    }
}

JJNG.Web/Areas/Branch/Views/BrhAddressAccount/CreateEdit.cshtml
@model JJNG.Data.Personnel.PsnAddressAccount

@{
    Layout = "_CreateEditLayout";
    var actionName = ViewContext.RouteData.Values["action"].ToString();
    var controllerName = ViewContext.RouteData.Values["controller"].ToString();
    var areaName = ViewContext.RouteData.Values["area"].ToString();
    ViewData["action"] = actionName;
    ViewData["controller"] = controllerName;
    ViewData["area"] = areaName;
}
<div asp-validation-summary="ModelOnly" class="text-danger"></div>
@if (ViewData["action"].ToString() == "Create")
{ }
else
{
    <input type="hidden" asp-for="AddressAccountId" />
}
<div class="col-md-12">
    <div class="form-group">
        <label asp-for="AccountName" class="control-label"></label>
        <input asp-for="AccountName" class="form-control" />
        <span asp-validation-for="AccountName" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Manager" class="control-label"></label>
        <input asp-for="Manager" class="form-control" />
        <span asp-validation-for="Manager" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Department" class="control-label"></label>
        <select asp-for="Department" asp-items="ViewBag.Department" class="form-control"></select>
        <span asp-validation-for="Department" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Branch" class="control-label"></label>
        <select asp-for="Branch" asp-items="ViewBag.Branch" class="form-control"></select>
        <span asp-validation-for="Branch" class="text-danger"></span>
    </div>
</div>
@Html.Partial("_ValidationScriptsPartial")

JJNG.Web/Areas/Branch/Views/BrhAddressAccount/Index.cshtml
@model IEnumerable<JJNG.Data.Personnel.PsnAddressAccount>

@{
    var actionName = ViewContext.RouteData.Values["action"].ToString();
    var controllerName = ViewContext.RouteData.Values["controller"].ToString();
    var areaName = ViewContext.RouteData.Values["area"].ToString();
    ViewData["action"] = actionName;
    ViewData["controller"] = controllerName;
    ViewData["area"] = areaName;
    ViewData["Title"] = controllerName;
    string path = "/" + areaName + "/" + controllerName;
}
<section class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="box box-primary ">
                <div class="box-header with-border">
                    <h3 class="box-title">通讯录管理<small class="hidden-xs" style="color:red">&emsp; @ViewData["Branch"].ToString() &nbsp;·&nbsp; @ViewData["UserName"].ToString()</small></h3>
                    <div class="box-tools pull-right">
                        <button type="button" class="btn btn-box-tool" data-widget="collapse">
                            <i class="fa fa-minus"></i>
                        </button>
                        <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
                    </div>
                </div>
                <div class="box-body table-responsive">
                    <div class="form-group">
                        <div class="col-md-3 col-sm-6 col-xs-12 no-padding pull-right">
                            <input type="text" placeholder="搜索" id="search" class="form-control">
                        </div>
                    </div>
                    <table id="table-1" class="table  table-bordered table-striped table-hover" width="100%">
                        <thead>
                            <tr>
                                <th>
                                    @Html.DisplayNameFor(model => model.AccountName)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Manager)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Department)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Branch)
                                </th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.AccountName)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Manager)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Department)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Branch)
                                    </td>
                                    <td>
                                        <a asp-action="Index" asp-controller="BrhAddress" asp-route-area="Branch" asp-route-id="@item.AddressAccountId" class="btn-sm btn-primary" style="width:70px;margin-right:5px; min-width:50px;">
                                            <i class="glyphicon glyphicon-plus"></i> 查看
                                        </a>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</section>
@section Scripts{
    <script>
        $(function () {
            //#region table1初始化
            var table1 = $('#table-1').dataTable(
                {
                    responsive: true,
                    order: [[0, "desc"]],
                    dom:
                        "<'row'<'col-sm-6'><'col-sm-6'>>" +
                        "<'row'<'col-sm-12'tr>>" +
                        "<'row'<'col-sm-5'i><'col-sm-7'p>>",
                    language: {
                        processing: "加载中...",
                        lengthMenu: "每页显示 _MENU_ 条数据",
                        zeroRecords: "没有匹配结果",
                        info: "显示第 _START_ 至 _END_ 项结果，共 _TOTAL_ 项",
                        infoEmpty: "显示第 0 至 0 项结果，共 0 项",
                        infoFiltered: "(由 _MAX_ 项结果过滤)",
                        infoPostFix: "",
                        search: "搜索:",
                        url: "",
                        emptyTable: "没有匹配结果",
                        loadingRecords: "载入中...",
                        thousands: ",",
                        paginate: {
                            first: "首页",
                            previous: "上一页",
                            next: "下一页",
                            last: "末页"
                        },
                        aria: {
                            sortAscending: ": 以升序排列此列",
                            sortDescending: ": 以降序排列此列"
                        }
                    },
                });
            $("#search").keyup(function () { table1.api().search($("#search").val()).draw(); });
            //#endregion
        });
    </script>
}